// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATsRH2fDJ4l26Pmo_zo59ST2R6znjUJXk',
    appId: '1:958846432617:web:c83282bb841e99096439f8',
    messagingSenderId: '958846432617',
    projectId: 'fruits-app-a4e27',
    authDomain: 'fruits-app-a4e27.firebaseapp.com',
    storageBucket: 'fruits-app-a4e27.firebasestorage.app',
    measurementId: 'G-GND8WDNDXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp3qMvVPy1dVmitB_8X51Y0Z27ByDNxYQ',
    appId: '1:958846432617:android:a6d37e8a039261ba6439f8',
    messagingSenderId: '958846432617',
    projectId: 'fruits-app-a4e27',
    storageBucket: 'fruits-app-a4e27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAACU4wytNeCnpEVOihABKNJHLP-JFuKio',
    appId: '1:958846432617:ios:76c6554087408f566439f8',
    messagingSenderId: '958846432617',
    projectId: 'fruits-app-a4e27',
    storageBucket: 'fruits-app-a4e27.firebasestorage.app',
    iosBundleId: 'com.example.fruitsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAACU4wytNeCnpEVOihABKNJHLP-JFuKio',
    appId: '1:958846432617:ios:76c6554087408f566439f8',
    messagingSenderId: '958846432617',
    projectId: 'fruits-app-a4e27',
    storageBucket: 'fruits-app-a4e27.firebasestorage.app',
    iosBundleId: 'com.example.fruitsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATsRH2fDJ4l26Pmo_zo59ST2R6znjUJXk',
    appId: '1:958846432617:web:2361eff8071dae1f6439f8',
    messagingSenderId: '958846432617',
    projectId: 'fruits-app-a4e27',
    authDomain: 'fruits-app-a4e27.firebaseapp.com',
    storageBucket: 'fruits-app-a4e27.firebasestorage.app',
    measurementId: 'G-4XYDV3LGCW',
  );
}
